### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kgraefe** [ChristianGalla/PidginWinToastNotifications#1]
The PidginWinToastNotifications part of your plugin uses `GPLv2` code from Pidgin and therefore must be licensed under `GPLv2` itself. (GPL code can use MIT code, but not the other way around, see https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility)

**Comment by ChristianGalla** [comment]
Thanks for the hint.
I have switched to GPLv2, so the program should now follow the Pidgin license.
