### ISSUE TITLE
Not working on Pidgin 2.12.0

### ISSUE THREAD

**Issue by b2cbd** [ChristianGalla/PidginWinToastNotifications#12]
The latest version 1.6.1 doesn't work on Pidgin 2.12.0 / Windows 10-x64,  can't enable the plugin from the plugin list.

Though it works on 2.13.0.  For older plugins, many of us need to use Pidgin 2.12.0.

1.5.0 version works on 2.12.0

**Comment by ChristianGalla** [comment]
Thanks for reporting this bug.

I am usually only programming for the newest Pidgin version and have never tested an older version.

If an older Pidgin version is used, the plugin may call a Pidgin function that not exists and therefore fails.
That is the reason I suggest using the newest Pidgin version.

If it is not possible to use the newest Pidgin version, can you please have a look in the error search window and let me know, if there are any plugin related error messages?

**Comment by b2cbd** [comment]
@ChristianGalla  Thanks for checking out the issue. Here is the debug log for `1.6.1`!

```
plugins: probing C:\Program Files (x86)\Pidgin\plugins\PidginWinToastNotifications.dll
plugins: C:\Program Files (x86)\Pidgin\plugins\PidginWinToastNotifications.dll is not loadable: ABI version mismatch 2.13.x (need 2.12.x)
```

**Comment by ChristianGalla** [comment]
I have build the plugin for Pidgin 1.12.0 and [attached it to the last release](https://github.com/ChristianGalla/PidginWinToastNotifications/releases/download/v1.6.1/PidginWinToastNotifications.for.Pidgin.1.12.0.zip).

Can you please test if it works on your machine?

**Comment by b2cbd** [comment]
@ChristianGalla  Thanks I used lib file form `1.6.1` and this `DLL` - **I confirm it works in Pidgin 2.12.0 (libpurple 2.12.0).** 

There could be an enhancement for the next version. For some protocols like `Whatsapp/Facebook`, when I logged in using Pidgin but send a message using my phone app, this plugin shows notification for my own message with the wrong sender name. It could filter notification for only incoming messages, not the outgoing ones.

I really appreciate all the hard work you've done here.

**Comment by ChristianGalla** [comment]
When you send a message via phone, which sender name is displayed in Pidgin?

Are there protocols where this does not happen?

If this is a protocol specific issue, this issue may be in the scope of the protocol plugin.

**Comment by b2cbd** [comment]
@ChristianGalla  This happens only for [WhatsApp](https://github.com/hoehermann/purple-gowhatsapp) and [Facebook](https://github.com/dequis/purple-facebook) protocol, they are the `HTTP` protocol. Other protocols like `Google-XMPP` is fine.

It shows the `receiver-name` on notification, though it was an outgoing message.  It supposes to show notification only for incoming messages. In the chat window, it shows my name correctly for this message.

**Comment by ChristianGalla** [comment]
@b2cbd It seems you have created [an issue in the WhatsApp plugin](https://github.com/hoehermann/purple-gowhatsapp/issues/32) and there was [a commit addressing the issue about receiving of own messages that were send from another device](https://user-images.githubusercontent.com/7421161/71769080-b75aea80-2f1c-11ea-81a2-0a0e400a7015.png). I hope the next Windows build of the WhatsApp plugin fixes this issue.

Because the initial issue (working on Pidgin 2.12.0) was resolved and it looks like the other issue you reported is in the scope of the protocol plugins, I am closing this issue.
If you are experiencing any additional issues or have a feature request feel free to open a new issue.
