### ISSUE TITLE
Cannot enable plugin

### ISSUE THREAD

**Issue by Reagn0x** [ChristianGalla/PidginWinToastNotifications#13]
I cannot enable the plugin with a standard user, on the debug I have this message :

> (11:52:24) win_toast_notifications: loading...
> (11:52:24) win_toast_notifications: dll loaded
> (11:52:24) win_toast_notifications: pidginWinToastLibInit called
> (11:52:24) win_toast_notifications: Initialization failed: The library was not able to create a Shell Link for the app

It works perfectly with an Administrator user.

This is on a RDS farm with Windows Server 2016 (1607 14393.3443) with Active Directory GPO for standard users and roaming profiles.

**Comment by ChristianGalla** [comment]
A requirement of Microsoft's Toast Notification API is that there must be a start menu shortcut for the app that is using the API.

When there is no shortcut, the plugin tries to create a temporary one. I assume, in your environment a normal user is not permitted to create a start menu shortcut, so the quoted error message is created.

Usually Pidgin's installer creates a start menu shortcut. Can you please verify if there is a start menu shortcut for Pidgin? If not, can you create one?

**Comment by Reagn0x** [comment]
Hi,

Yes there is a shortcut

![pidgin](https://user-images.githubusercontent.com/9754845/73165530-401c0f00-40f4-11ea-907d-7c24d30141bd.png)

**Comment by Reagn0x** [comment]
Hello,

The problem is solved, there was a problem with the rights of the folder for the users : %AppData%\Microsoft\Windows\Start Menu\Programs

With the good ACL, the shortcut is created and the plugin is activated.
