### ISSUE TITLE
Plugin greyed out

### ISSUE THREAD

**Issue by Industry** [ChristianGalla/PidginWinToastNotifications#14]
I have installed the DLLs for a Windows build of Pidgin but when I try to enable to plugin, it appears grayed out. Do you know what could be causing this?
[Screenshot](https://i.imgur.com/CMmu0ye.png)

**Comment by ChristianGalla** [comment]
Please ensure, you are using a supported Pidgin and Windows Version as described in the Readme.

If this is not fixing your problem, please check the error search window. There should be a toast notification error.

**Comment by Industry** [comment]
I was using an older version. Upgrading to v2.14.1 fixed the issue. Perhaps there should be a check somewhere to prevent confusion in the future?

**Comment by ChristianGalla** [comment]
Version compatibility is already checked by Pidgin itself before the Plugin is loaded. Because of the incompatibility it was greyed out.

Supported versions of Pidgin are already mentioned in the Readme right before the install instructions, so I think for now no further action is needed.

**Comment by Industry** [comment]
Guess then pidgin needs to do a better job of letting the user know the plugin is incompatible. Oh wells. Thanks Christian.
