### ISSUE TITLE
Notifies of message received by user even when user's window is in focus

### ISSUE THREAD

**Issue by instinctualjealousy** [ChristianGalla/PidginWinToastNotifications#2]
Great plugin by the way. Really needs added to the Pidgin ThirdPartyPlugins list, hard to find.

Anyway, as of right now, for me at least (I assume I haven't messed anything up on my end), the plugin will push notifications even when a user's window is in focus, which is a bit much. Maybe either change the default behavior to ignoring messages received in a focused window, or provide an option in the plugin configuration to toggle it?

**Comment by ChristianGalla** [comment]
Thanks for the feedback.
Yes, I think notifications should only be shown if the window is not in focus, too.
Luckily this feature was very easy to add. So, I implemented it directly. :-)

**Comment by ChristianGalla** [comment]
The plugin is now listed in Pidgin's list of third party plugins.
