### ISSUE TITLE
Disable notifications when away

### ISSUE THREAD

**Issue by EionRobb** [ChristianGalla/PidginWinToastNotifications#3]
When my account is away, I would like the option to disable notifications so that I am not getting pinged while I'm in a meeting.

**Comment by ChristianGalla** [comment]
In [the new options](https://github.com/ChristianGalla/PidginWinToastNotifications/issues/5#issuecomment-395870331) it is possible to toggle notifications per primitive status (Available, Away, Do not disturb, Extended away and Invisible).

I think this satisfies the most users.
