### ISSUE TITLE
Setting the app id creates a dup icon

### ISSUE THREAD

**Issue by EionRobb** [ChristianGalla/PidginWinToastNotifications#4]
![image](https://user-images.githubusercontent.com/1063865/40893619-bce63b74-67f6-11e8-98e3-de39625dc5fc.png)

Setting the app id causes the pinned taskbar icon to be duplicated

**Comment by ChristianGalla** [comment]
The app id must be set so the notifications can be associated to the program and Window's notification API can be called.
I do not have found that the app id is set by Pidgin or its installer so I set it to "GallaChristian/Pidgin" on initialization of the plugin.
A quick fix is to unpin the old icon and pin the running window to the taskbar.

**Comment by EionRobb** [comment]
This conflicts with the pidgin-win7 plugin, so it will always show with a second icon if used in combination with that plugin

**Comment by ChristianGalla** [comment]
If I skim read the code correctly, the pidgin-win7 plugin sets the app id "Pidgin.Win7Plugin" which in fact collides with "GallaChristian.Pidgin".

I think a standardized app id for Pidgin is needed, which is shared by all Windows plugins that have to use it.

According to [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx#HOW) the App Id should have the format "CompanyName.ProductName.SubProduct.VersionInformation" while the CompanyName and ProductName should be used and SubProduct and VersionInformation are optional.

I therefore suggest "Pidgin.Pidgin" as app id to be used by all plugins.

Should this somewhere in the Pidgin community be discussed or are our plugins the first and only ones that hit this issue?

After agreeing on an app id I think this should be noted in the Pidgin wiki for other developers.
