### ISSUE TITLE
Options for notifications

### ISSUE THREAD

**Issue by EionRobb** [ChristianGalla/PidginWinToastNotifications#5]
Similar to the Message Notifications plugin (or if you can use the options/settings that it provides)
![image](https://user-images.githubusercontent.com/1063865/40893664-36ef339e-67f7-11e8-8843-4a5c8c5cc01c.png)

To be able to only get notifications for chats where I'm mentioned, or for IM's.  I'm connected to a lot of noisy chats and I don't want to see every message for every conversation.

**Comment by ChristianGalla** [comment]
I have added options to configure when toast notifications should be shown:

![image](https://user-images.githubusercontent.com/7421161/41177822-b6598b04-6b65-11e8-9bd8-ce8c59b16c20.png)

I think system messages should never be shown. Also, I think the plugin should focus on the toast notifications and not modify conversation windows. Therefore, I have omitted these options and only implemented "notify for" options.

Is it good like that?
